[package]
name = "scribbles"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.5"
anyhow = "1.0.97"
env_logger = "0.11.8"
log = { version = "0.4.27", features = ["kv"] }
rand = "0.9.0"
tokio = { version = "1.44.1", features = ["full"] }
